In [13]:
from sklearn import datasets, metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np

dataset = datasets.load_iris()
X = pd.DataFrame(dataset.data)
y = pd.DataFrame(dataset.target)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train.values.ravel())
y_prediction = knn.predict(X_test)

print('K-Nearest Neighbour Accuracy : ', metrics.accuracy_score(y_test, y_prediction))
print("Confusion Matrix : \n", metrics.confusion_matrix(y_test, y_prediction))




K-Nearest Neighbour Accuracy :  0.9333333333333333
Confusion Matrix : 
 [[19  0  0]
 [ 0 16  0]
 [ 0  4 21]]


In [17]:
print(y_prediction)

[1 2 0 2 0 2 1 0 0 2 1 0 2 1 0 1 2 0 2 1 0 1 1 0 1 2 2 0 1 2 2 0 0 2 1 1 1
 0 0 2 1 2 1 2 0 2 2 1 2 1 1 1 1 2 0 0 0 0 2 2]


In [19]:
print(y_test)


     0
73   1
129  2
24   0
148  2
41   0
118  2
51   1
39   0
46   0
145  2
61   1
31   0
123  2
95   1
30   0
66   1
144  2
18   0
135  2
63   1
32   0
126  2
69   1
45   0
53   1
134  2
132  2
5    0
106  2
143  2
147  2
0    0
16   0
110  2
138  2
91   1
90   1
27   0
4    0
146  2
82   1
102  2
93   1
114  2
28   0
136  2
124  2
56   1
149  2
64   1
119  2
75   1
85   1
108  2
8    0
11   0
14   0
29   0
116  2
120  2
