In [13]:
from sklearn import datasets, metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np

dataset = datasets.load_iris()
X = pd.DataFrame(dataset.data)
y = pd.DataFrame(dataset.target)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train.values.ravel())
y_prediction = knn.predict(X_test)

print('K-Nearest Neighbour Accuracy : ', metrics.accuracy_score(y_test, y_prediction))
print("Confusion Matrix : \n", metrics.confusion_matrix(y_test, y_prediction))




K-Nearest Neighbour Accuracy :  0.9333333333333333
Confusion Matrix : 
 [[19  0  0]
 [ 0 16  0]
 [ 0  4 21]]


In [ ]:
print()